In [2]:
import numpy as np


## numpy array

In [3]:
myList = [20,30,40]

In [4]:
np.array(myList)

array([20, 30, 40])

In [5]:
matrixList = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
matrixList[1][0]

4

In [7]:
np.array(matrixList)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Arange (çok önemli)

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [9]:
 np.arange(2,20,2) #2'den başla 20'ye kadar 2 şer 2 şer sırala

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

## Zeros \ Ones

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.ones((8,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

## Linspace (çok önemli)

In [14]:
np.linspace(0,20,16)

array([ 0.        ,  1.33333333,  2.66666667,  4.        ,  5.33333333,
        6.66666667,  8.        ,  9.33333333, 10.66666667, 12.        ,
       13.33333333, 14.66666667, 16.        , 17.33333333, 18.66666667,
       20.        ])

## Eye

In [15]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [16]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random

In [17]:
np.random.randn(4)

array([ 0.10093194, -0.55279869, -0.42407595,  2.00562368])

In [18]:
np.random.randn(4,4)

array([[ 0.81368529,  0.22862538, -0.43693362,  0.21112251],
       [ 0.3945026 , -1.27790453, -0.50694666,  1.19271403],
       [ 0.0790076 ,  0.57714157,  0.43231021,  1.32948057],
       [-1.74637196,  0.76158037,  0.7153748 , -1.17337149]])

In [19]:
np.random.randint(1,10)

5

In [20]:
np.random.randint(1,300,5) # 1'den 300'e kadar 5 adet rastgele sayı verir.

array([126, 163, 261, 299, 213])

In [21]:
myRandomArray = np.random.randint(0,100,30)

In [22]:
myRandomArray

array([11, 80, 69, 56,  1, 57, 92, 63, 71, 96, 21, 38, 54, 64, 37, 54, 49,
       12, 89, 14, 16, 51, 37, 50, 62, 20, 33, 50, 59, 63])

## Numpy Dizi Methodları

In [23]:
myNumpyArray.reshape(5,6)

NameError: name 'myNumpyArray' is not defined

In [ ]:
myRandomArray.reshape(5,6)

array([[39, 44, 55, 56, 62, 62],
       [15, 96, 66, 76, 18, 40],
       [61, 58, 71, 93,  4,  3],
       [ 4, 69, 28, 11,  1, 61],
       [63, 43, 31,  1, 91, 12]])

In [ ]:
myRandomArray.max()

96

In [ ]:
myRandomArray.min()

1

In [ ]:
myRandomArray.argmin() ## en küçük sayının indexini verir.


22

In [27]:
benimDizim2 = np.arange(0,15)
benimDizim2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
benimDizim2[3:8]

array([3, 4, 5, 6, 7])

In [33]:
benimDizim2[3:8] = -5 # 3'ten 8'e kadar olan sayıları değiştirir.
benimDizim2

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [39]:
baskaDizi = np.arange(0,24)
slicingDizisi = baskaDizi[4:9]
baskaDizi
slicingDizisi

array([4, 5, 6, 7, 8])

In [41]:
slicingDizisi[:] = 700 #slicingDizisi'ndeki rakamların hepsini kapsar ve bunları atanan değer ile değiştirir
slicingDizisi

array([700, 700, 700, 700, 700])

In [42]:
baskaDizi #slicingDizisi'nde atanan değer ana dizide de değişikliğe gidilir.

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

dizi kopyalayıp işlem yapma

In [43]:
ornekDizisi = np.arange(0,24)
ornekDizisi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [44]:
ornekDiziKopyasi = ornekDizisi.copy()
ornekDiziKopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [46]:
ornekdiziSlicing = ornekDiziKopyasi[3:6]
ornekdiziSlicing[:] = 800
ornekdiziSlicing

array([800, 800, 800])

In [48]:
ornekDiziKopyasi 

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [49]:
ornekDizisi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [51]:
# eğer bir np dizisinde işlem yapılacak ve bozulması istenmiyorsa, dizi kopyası oluşturulur.

MATRİX ISLEMLERI

In [52]:
benimListem = [[10,20,30],[20,30,40],[40,50,60]]
benimMatrixDizim = np.array(benimListem)

In [53]:
benimMatrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [69]:
benimMatrixDizim[0]
benimMatrixDizim[1,2]
benimMatrixDizim[0:,2:]


array([[30],
       [40],
       [60]])

In [88]:
yeniListe =[[10,20,30,90],[20,30,40,80],[40,50,60,65],[39,90,19,12]] #bütün listelerin içindeki değer sayıları aynı olmalı.

In [89]:
yeniMatrix2 = np.array(yeniListe)

In [90]:
yeniMatrix2

array([[10, 20, 30, 90],
       [20, 30, 40, 80],
       [40, 50, 60, 65],
       [39, 90, 19, 12]])

In [93]:
yeniMatrix2[[0,2,2]]

array([[10, 20, 30, 90],
       [40, 50, 60, 65],
       [40, 50, 60, 65]])

OPERASYONLAR

In [99]:
yenibirDizi = np.random.randint(1,100,20)
yenibirDizi

array([11,  8, 79, 91,  7, 16, 86, 38, 36, 96,  3, 27, 71, 63, 52, 56, 96,
       40, 36, 70])

In [101]:
sonucDizisi = yenibirDizi >24

In [102]:
yenibirDizi[sonucDizisi] #filtreleme için kullanıldı.

array([79, 91, 86, 38, 36, 96, 27, 71, 63, 52, 56, 96, 40, 36, 70])

In [103]:
sonDizi = np.arange(0,24)
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [104]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [105]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [106]:
sonDizi - sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])